spring:
    application:
        name: ms-item

    config:
        # Config server url
        import: configserver:http://localhost:8888
    
    graphql:
        graphiql:
            enabled: true
    
  